### ISSUE TITLE
Scrolling above the top causes seem weird graphical errors

### ISSUE THREAD

**Issue by sgpthomas** [lainsce/palaura#12]
Here is a gif showing it happening. All that I am doing here is scrolling up at the top of the list.

![broken](https://user-images.githubusercontent.com/3752122/30696623-3e702b8a-9eaa-11e7-835f-0a3574ce21f6.gif)

**Comment by lainsce** [comment]
Yeah, I fixed this in master, I'm still moving to another API, then I'll push a new release :smile:
