### ISSUE TITLE
could you make a flatpak for palaura?

### ISSUE THREAD

**Issue by altntowin** [lainsce/palaura#19]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for palaura?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by lainsce** [comment]
I am in the process of making a flatpak for Quilter, and is taking all my time in this. 😞

**Comment by altntowin** [comment]
i see , thanks for your effort.
i hope to see the application someday on flatpak format.
:)

**Comment by lainsce** [comment]
Gonna close this since I'm going to do the flatpak later.
