### ISSUE TITLE
Add Slingshot plugin

### ISSUE THREAD

**Issue by jtrees** [lainsce/palaura#21]
Palaura is great but sometimes I find myself wishing for a more integrated and less intrusive way to lookup words.

Is there are chance you could develop a Slingshot plugin (like [these](https://github.com/elementary/applications-menu/tree/master/lib/synapse-plugins)) so we can lookup words directly from the applications menu?

**Comment by lainsce** [comment]
I'll think of a way to do it :heart:

**Comment by jtrees** [comment]
Sweet! I look forward to it.

**Comment by lainsce** [comment]
I've just finished talking with an elementary core developer, and I'm not supposed to make a plugin for slingshot at this time. There's no custom app support yet.

**Comment by jtrees** [comment]
Aw, that's a shame. Thanks for the update though. Is it a feature on their roadmap? Is there an issue where we can track progress towards it?

**Comment by lainsce** [comment]
I believe Juno.1 or Juno+1 might have it.
