### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by torikulhabib** [lainsce/palaura#24]
## Hello! If you found an error in this app, follow this template:

* offline
* read sqlite example.db
* juno

Thanks!

**Comment by lainsce** [comment]
I don't understand your issue with the app, can you explain further? Is it that you want offline mode?

**Comment by torikulhabib** [comment]
i have this database offline for indonesian 
can you merge on your app
https://mega.nz/#!9LQSUQjB!tNNgx1OaW051X4OSTjMso0jtLNsa8movaEyDQTdsx_k

**Comment by lainsce** [comment]
My app doesn't work with databases, it uses an online API to fetch words and their definitions and stuff.
