### ISSUE TITLE
Support for Tweaks and Dark Themes

### ISSUE THREAD

**Issue by knorquist** [lainsce/palaura#26]
Text is almost impossible to read when "prefer dark variant" is toggled on in elementary tweaks. The text color switches to light, but since the background doesn't change color it's basically unreadable.

I know it's not a big deal, but it would be nice to be able to use Palaura (which is awesome, thank you!) at night with my dark theme on. Just a simple way to change the background color or something would be perfect.

![screenshot from 2018-10-20 14-03-45](https://user-images.githubusercontent.com/3306524/47260493-8e624d00-d471-11e8-9d91-36ca460b8643.png)

**Comment by lainsce** [comment]
Sorry, but once you mentioned Tweaks, you're on your own. Closing the issue.
