### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/palaura#27]
Translation files are missing (don't forget to add `appdata.xml`)

**Comment by lainsce** [comment]
Don't spam my repositories with issues if it's a simple fix like adding a file to add translations. There is an appdata file in the `data` subfolder in all of my apps...

**Comment by NathanBnm** [comment]
@lainsce Sorry I didn't notice it would be so many alerts, I didn't want to spam, just help.
There is an appdata file it is true but it is not included in the translation files.

**Comment by lainsce** [comment]
Make a simple Pull Request adding the fix wherever you see the file not being in the translations file. :smile:

**Comment by NathanBnm** [comment]
But I don't know how to add these strings in all language files at the same time.

**Comment by NathanBnm** [comment]
@lainsce changes are made for Palaura, I will look what I can do for the others apps. I opened #28

**Comment by NathanBnm** [comment]
All these apps have been translated. I've done PR for that. Closing.
