### ISSUE TITLE
Feature Request: Offline dictionary support

### ISSUE THREAD

**Issue by uncertainquark** [lainsce/palaura#34]
Need ability to view meanings of words offline. In fact, if that's the default, results would be fetched much faster. 

You could also make the entire app a floating window type (like [Clipped](https://appcenter.elementary.io/com.github.davidmhewitt.clipped/)) that is invoked with a hotkey and goes away on hitting escape key. It would make the app feel fast and apt for a utility like this.

**Comment by lainsce** [comment]
I am in the process of changing the backend to a completely offline one;
It takes time.

**Comment by lainsce** [comment]
Still changing the backend. Hope I can release before July...

**Comment by uncertainquark** [comment]
Thanks a lot for working towards this. I'd definitely pay for the app with this feature built-in. Having said that, no hurries from my side, take your time, you are the boss!

**Comment by NathanBnm** [comment]
Personally I don't feel comfortable about using a floating window with a shortcut like Clipped. I think it can be an option in the app settings. I have troubles with shortcuts in elementary. Some of them are conflicting. But I like the idea of an offline dictionary. 

Is there a way to use more different languages with an offline API?

**Comment by lainsce** [comment]
Yes, with an offline API, like WordNet (which is what I'll rewrite Palaura to use), I can get more languages working.

**Comment by lainsce** [comment]
If anyone's up for implementing WordNet as a PR, I'd be very thankful.

**Comment by lainsce** [comment]
Going to close this as it's nigh impossible to find a good offline API.
