### ISSUE TITLE
Doesn't find meaning of all words. like detrimental for example. 

### ISSUE THREAD

**Issue by gopichigo** [lainsce/palaura#41]
Hello,

Please update dictionary and also add dictionary preferences to choose from english oxford or cambridge. I think that wikipedia can be useful and a fandom wikipedia will be awesome. Spanish is useful but I haven't the foggiest of spanish language. Please also add french too, It is very helpful. I like the app it is lightweight and simple. 

That is all I have to say, i will report issue or ideas to make beautiful application if something comes up...
Thank you in advance.

**Comment by lainsce** [comment]
Hi,

This app is currently in a paused state. It will not recieve updates or bug fixing as still no fix was made for the use of an Offline dictionary.
Please understand.
