### ISSUE TITLE
Feature Request: Ability to search a word from command line

### ISSUE THREAD

**Issue by codemedic** [lainsce/palaura#45]
Something similar to gnome-dictionary.
It makes it possible to then grab text from clipboard and invoke Palaura from command line or shortcut or a script.

**Comment by codemedic** [comment]
Or you could provide clipboard integration in the app, but still I like the customisability of the comandline. Both please ... :P

**Comment by lainsce** [comment]
Sorry, but Palaura is going to be app-only; there's loads of options for commandline users already. I don't have control over the styling of your terminal, so, showing results would be subpar.
