### ISSUE TITLE
Feature request: provide word search from command-line

### ISSUE THREAD

**Issue by phase1geo** [lainsce/palaura#48]
I was wondering if it would be possible to to make a command-line call to Palaura that would allow the caller to pass a word to search for from the command-line. Preferably, if a second command was called with a different word and the application was opened, it would not cause a second window to be created (but that is not as important for this feature request).

**Comment by lainsce** [comment]
Sadly, I can't provide this functionality due to the terms of service of the API, which states only programs/apps and no CLI application may be used with this API.

**Comment by phase1geo** [comment]
I’m confused. Palaura isn’t a CLI application (at least in the sense that it takes input from standard input and provides output to standard output — any non-CLI application can be started from a command-line).

I’m not suggesting that you provide the result of the lookup to standard output for the purposes of scripting out definition lookups, I just want to provide the search term for the search field that exists within the app from the command-line. Surely, the terms of use wouldn’t restrict that.

I have an application that I would like to highlight a term, click a button, and launch Palaura with that term so that it can be displayed within your app. Of course, the user could do the same  with the clipboard and app launcher, but would be even more convenient by just clicking a button.

**Comment by lainsce** [comment]
It does restrict that, because you'd be using my api key to perform the search from your app using my app. Yeah, it's dumb, but nothing I can do.

**Comment by phase1geo** [comment]
I was just looking over the Oxford Dictionary terms of use page, and I don't see a conflict here. This is not a case of providing a separate API (6.1.7). The search and presentation of the data is completely restricted to your application. My app is just helping the user use your app by launching your application and providing the term to search for.

Looked at from a different perspective, if you take my application (or anyone else's) out of the equation, you are restricting the user from launching your application from the command-line, specifying a search term to use from that command-line. As long as your application doesn't supply some sort of dictionary result back to the command-line or write it to a file or copy the result to the clipboard, you aren't using your API key on behalf of other applications.

Is there some sort of restrictions that were provided to you that are not listed on their terms of use webpage?

**Comment by phase1geo** [comment]
I think I've said everything that I wanted to say on this issue, so I'll stop bother you now :)

**Comment by lainsce** [comment]
The restriction here is to share **API key** to another app technically. This would mean racking up searches and more money I have to pay from my pocket.
Each 1000 or so searches means more money in the end-of-month bill.
