### ISSUE TITLE
Feature request: provide synonyms and antonyms

### ISSUE THREAD

**Issue by phase1geo** [lainsce/palaura#49]
It would be pretty cool if Palaura would provide synonyms and antonyms for a given word in addition to its definition. If this is a feature that is possible, it would be even cooler if the synonyms and antonyms could be clicked on to automatically display their definition as well.

**Comment by lainsce** [comment]
I can provide them, but to link them inside the app I can't, because it's content that is live-updated.

**Comment by lainsce** [comment]
Fixed in the 2.0 (Next) release. On hold until Odin.
