### ISSUE TITLE
Change required for AppCenter: Searching doesn't work on a fresh install

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/palaura#51]
The default language code in GSettings is `en-US`, but the API requires `en`. As such, out of the box Palaura only returns errors because it's presumably hitting the wrong API endpoint.

https://github.com/lainsce/palaura/blob/eb1e964d88f0dc4e10346702d41081b7d5903976/data/com.github.lainsce.palaura.gschema.xml#L19

**Comment by lainsce** [comment]
Fixed. :sweat_smile:
