### ISSUE TITLE
Scale?

### ISSUE THREAD

**Issue by hvze** [lainsce/palaura#7]
I don't have elementary installed, but I feel like this would be better if the window scaled (if the amount of text was small) to the text, rather than have all that space wasted.

**Comment by lainsce** [comment]
The problem with that is that I can't automatically predict how many entries inside a search term like "elementary", I will have, and work on it magically like that. Also, GTK has some limitations on that part too.

**Comment by hvze** [comment]
You could scale it with a nice animation after you get the results :)

**Comment by lainsce** [comment]
Yeah, GTK doesn't do fancy animations like that. It's one of the limitations I broadly mentioned.

**Comment by hvze** [comment]
ah okay, what a shame.
