### ISSUE TITLE
Create a gresource for your css instead of a constant

### ISSUE THREAD

**Issue by danrabbit** [lainsce/palaura#9]
instead of storing your stylesheet as a contast in a vala file, you should create a gresource and load it from the resource. 

Felipe recently did something similar, so [here's a handy diff](https://github.com/Philip-Scott/Spice-up/commit/ddc463b66a3a5565fbf0be46eae4844b53bc10df) :)

**Comment by lainsce** [comment]
Will try it out once the API move is finished. :)

**Comment by lainsce** [comment]
Fixed in master
